### ISSUE TITLE
Option to leave out suffix when title is default

### ISSUE THREAD

**Issue by TheWrongAlice** [vinaygopinath/ngMeta#12]
I would like to have a title suffix that always applies automatically `ngMetaProvider.useTitleSuffix(true);` but _not_ when the default title is being used.

so to put this into an example, if I use this configuration

```
ngMetaProvider.setDefaultTitle('Site name');
ngMetaProvider.useTitleSuffix(true);
ngMetaProvider.setDefaultTitleSuffix(' | Site name');
```

then

```
meta: {
  title: 'Page name' // Gives me the title "Page name | Site name"
}
```

and

```
meta: {} // Gives me the title "Site name"
```

**Comment by TheWrongAlice** [comment]
Here is my proposed solution:
Instead of true/false we can send in a string to this function:

```
ngMetaProvider.useTitleSuffix('always'); // Always adds a title suffix (same as 'true')
ngMetaProvider.useTitleSuffix('notDefaultTitle'); // Always adds a title suffix, unless the title is the default title
ngMetaProvider.useTitleSuffix('never'); // Never adds a title suffix (same as 'false') (default)
```

The function must still support a true/false as well, so that it doesn't break when people upgrade.

**Comment by vinaygopinath** [comment]
I'm concerned that this might be an uncommon use-case that might add complexity to the configuration. This can presently be addressed in two ways:

**When most states use a titleSuffix (#4)**
Module config:

``` javascript
ngMetaProvider.useTitleSuffix(true);
ngMetaProvider.setDefaultTitleSuffix(' | Site name');
```

States that shouldn't use the titleSuffix

``` javascript
meta: {
  titleSuffix: '' //Override default suffix
}
```

**When most states don't use a titleSuffix**
Module config:

``` javascript
ngMetaProvider.useTitleSuffix(true);
```

States that should use a titleSuffix

``` javascript
meta: {
   titleSuffix: ' | This page has a suffix'
}
```

**Comment by vinaygopinath** [comment]
I'm closing this issue for now. I'll revisit it if there are more requests for this feature. Thanks for your input @TheWrongAlice
