### ISSUE TITLE
Broken ngMeta demo

### ISSUE THREAD

**Issue by yobre** [vinaygopinath/ngMeta#16]
![schermata 2016-09-14 alle 10 33 14](https://cloud.githubusercontent.com/assets/5311396/18505324/f41b269c-7a66-11e6-8378-b677f097f4e7.png)

Hi all,
i'm trying to test your [demo site](http://vinaygopinath.github.io/ngMeta/#/example/dynamic-tags) on facebook debugger page and doesn't work. It's normal?

I've tried to use yours module for my app but it gives me the same results. Any suggestion?
thanks

**Comment by vinaygopinath** [comment]
Please refer to the [Support for other crawlers](https://github.com/vinaygopinath/ngMeta#support-for-other-crawlers) section of the README

**Comment by yobre** [comment]
Ok.
Now i understand.
But i've tried to post on G+ your demo site link and doesn't work. what am I doing wrong?

![schermata 2016-09-14 alle 12 22 01](https://cloud.githubusercontent.com/assets/5311396/18508847/3c7ba0ec-7a76-11e6-86d5-649b3a03f2b5.png)

**Comment by vinaygopinath** [comment]
Google and Google+ don't use the same bot to index websites - Googlebot fetches the HTML, executes Javascript, waits till rendering is complete (during which Angular and ngMeta are loaded, and ngMeta creates the tags based on your route/state configuration) and _then_ picks up the meta tag information from the page.

The bots of Google+, Facebook, Twitter and others simply fetch the HTML and, expecting the page to be static (either static HTML or pre-rendered server-side), grab the tags and values defined in <meta> elements. This is why Facebook sees the raw text "{{ngMeta.title}}", not "Example - Dynamic Tags | ngMeta - Customize meta tags from your controllers".

ngMeta, like any other Angular 1x SEO library, or indeed, Angular itself, is incapable of generating static HTML. ngMeta can only support crawler bots that execute Javascript.
