### ISSUE TITLE
On project build ngMeta does't work

### ISSUE THREAD

**Issue by prashant-andani** [vinaygopinath/ngMeta#18]
Hi,
I'm using grunt to build my project 
So on grunt serve, ngMeta works fine
on Grunt Build which creates a dist folder.. there ngMeta doesnt work
im trying to set the page title though

**Comment by vinaygopinath** [comment]
Please provide some information that would be useful to debug your situation while filing an issue.
1. What specifically does not work? I won't be able to help you based on "ngMeta doesn't work".
2. Do you have any console errors while running the built files in your dist folder?
3. Can you confirm that a meta tag with {{ngMeta.title}} is present in your dist/index.html file?
4. Are you updating your meta tags through route/state configuration, or dynamically (using `setTitle`)?
5. Is this a publicly hosted site/repo that I can look at?

**Comment by heshamelmasry77** [comment]
what is the solution for that
