### ISSUE TITLE
What about other meta tags

### ISSUE THREAD

**Issue by bdairy** [vinaygopinath/ngMeta#2]
Can we add other tags like keywords..author etc?

**Comment by totallytotallyamazing** [comment]
Yes I agree with @bdairy . Please @vinaygopinath what about that?

**Comment by vinaygopinath** [comment]
When I built this, it was for the purpose of using the basic meta tags listed in [ogp.me](http://ogp.me/#metadata), but adding support for other tags is straightforward and I'm open to that. Which tags would you like to see included?

If anyone wants to take a dig at it and send me a PR, that'd be cool too.

**Comment by apitts** [comment]
How about og:url?

**Comment by apitts** [comment]
Or a construct where you could set arbitrary meta tags. So, if you add the following to a route:

``` javascript
meta: {
  myCustomTagName1: 'myTagValue1',
  myCustomTagName2: 'myTagValue2'
}
```

You would then be able to do the following:

``` html
<meta property="myCustomTagName1" content="{{ngMeta.myCustomTagName1}}">
<meta property="myCustomTagName2" content="{{ngMeta.myCustomTagName2}}">
```

Replace myCustomTagName1 with og:url for example.

Thoughts?

**Comment by bdairy** [comment]
agree with @apitts  that would be great

**Comment by vinaygopinath** [comment]
Thanks @apitts. That's a great suggestion.
I've started working on this feature. I'll release a new version by the end of this week.

**Comment by bdairy** [comment]
@vinaygopinath I've added support for keywords and url.. I can send it to you personally to evaluate it and give me your feedback.. so maybe you can added to the repo.. but if yow implemented that enhancement you wont need to specify tags any more.

**Comment by vinaygopinath** [comment]
@bdairy Thanks for adding "keywords" and "url", but I think I'll make it more generic to support arbitrary tags without having to handle each of them separately.

**Comment by vinaygopinath** [comment]
Hey guys, sorry for the delay.
I've just updated ngMeta to 0.3.0 with support for arbitrary tags. **This release has breaking changes!**

In the app.js `run` block, please call the `init` function

``` javascript
angular.module('YourApp', ['ngRoute', 'ngMeta'])
.config(function($routeProvider, ngMetaProvider) {
  ....
})
.run(function(ngMeta) {
  ngMeta.init();
});
```

In the config phase, you can set defaults for arbitrary tags. You can continue to use `ngMetaProvider.useTitleSuffix(bool)`, `ngMetaProvider.setDefaultTitle(string)` and `ngMetaProvider.setDefaultTitleSuffix(string)`

``` javascript
ngMetaProvider.setDefaultTag('ogDescription', 'Placeholder description');
ngMetaProvider.setDefaultTag('og:sitename', 'Placeholder sitename');
```

In your routes/states, you can define any meta tag

``` javascript
meta: {
  'ogDescription': 'Description of the page',
  'og:image': 'http://example.com/b.png'
}
```

In your controllers, you can now use

``` javascript
ngMeta.setTag('og:image', 'http://example.com/a.png');
```

In your HTML, make sure you refer to tags with special characters in a JS-safe way

``` html
<meta property="og:image" content="{{ngMeta['og:image']}}" />
<meta property="og:description" content="{{ngMeta.ogDescription}}" />
```

Please confirm that this release works and I'll close this issue
Thanks for the input, everyone!
