### ISSUE TITLE
Facebook post

### ISSUE THREAD

**Issue by Valonix** [vinaygopinath/ngMeta#20]
Hi, when i post in Facebook url of website
it seems like 
http://ipic.su/img/img7/fs/kiss_16kb.1475926597.png
How can i fix it?

**Comment by vinaygopinath** [comment]
Please read the [README section about other crawlers](https://github.com/vinaygopinath/ngMeta#support-for-other-crawlers) and #16 

Short answer: Use a pre-renderer or server-side redirects for visits by Facebook bots.

**Comment by Valonix** [comment]
so, i put meta tags for facebook, but they don`t need because i need send from server side another data? So ,for what i need this lib? :)

**Comment by vinaygopinath** [comment]
The Facebook/open graph meta tags added through ngMeta are still relevant when you use a pre-renderer or render and serve pages statically on your server.

I've seen cases where people have used this library as a low-effort way to be indexed by Google (while still showing the ugly uninterpolated Angular expression in social media snippets)

**Comment by Valonix** [comment]
I use Laravel 5.2 and Angular 1.5.8 
As i understood, i need to detect bots and render another page for bots. =(
