### ISSUE TITLE
Google Indexing (Continuation of old ticket)

### ISSUE THREAD

**Issue by BobKlaas** [vinaygopinath/ngMeta#22]
I'm still having issues with Google Indexing on this site (www.klaasrealty.net). I wasn't able to resolve the issue. We had a ticket open that was closed several months ago. However, the issue never really resolved. I tried to concat and uglify my JS assets thinking that would help, but still no dice. Would love to put this issue to rest, but I'm at a loss for ideas.

![indexing](https://cloud.githubusercontent.com/assets/5191616/19533203/a0eae054-95f3-11e6-9501-33096c97a2e1.png)

**Comment by BobKlaas** [comment]
So, in order to fix this, I did three things. Everything is working now. You can close this issue.
1. Updated my ngMeta library to the most recent version.
2. Change my title tag to use ng-bind vs braces.
3. Concat and minfied my JS assets.

**Comment by vinaygopinath** [comment]
Hey @BobKlaas, glad to hear that you've managed to get it working!

I don't see how JS concat/minification could influence Google SERP snippets, but I do think point 2 had an effect on the titles.
