### ISSUE TITLE
ngMeta it's undefined in controller 

### ISSUE THREAD

**Issue by rafaelbsconsult** [vinaygopinath/ngMeta#24]
i'm use service ngMeta in controoller but dont work.
it's showing undefined in "console.log"

**Comment by vinaygopinath** [comment]
If you'd like to get support with your issue, please make sure there's enough information to work with - by providing additional information about the issue, along with a link to a plunkr/codepen.

How have you added ngMeta (npm, bower, CDN script)? Are you sure you've followed the steps listed in the README (adding 'ngMeta' as a module dependency)? Are there errors in your console?

**Comment by rafaelbsconsult** [comment]
Tks @vinaygopinath  i will not use it anymore module ;)

**Comment by chris-bytelion** [comment]
Same but injecting ngMeta at the beginning of my dependency list in my controller fixed it for me.

**Comment by chris-poe** [comment]
Same but injecting ngMeta at the beginning of my dependencies list in my controller fixed it for me.

**Comment by ghost** [comment]
Injecting ngMeta at the beginning of my dependencies list in my controller fixed this issue for me.
