### ISSUE TITLE
Not working with Webpack

### ISSUE THREAD

**Issue by mcgilly17** [vinaygopinath/ngMeta#27]
I tried using this with Webpack (using require and import) however i couldn't get it to work.

By making the following change: 

```
return angular.module('ngMeta', [])
```

It worked in webpack.

**Comment by mcgilly17** [comment]
@vinaygopinath can you check this please? we are hoping to use this in prod asap.

Thanks

McGilly

**Comment by Nargonath** [comment]
It would require a simple modification in the [ngMeta.js](https://github.com/vinaygopinath/ngMeta/blob/36ce954b51bb82161fd9772bb42fcc94035f7b9f/src/ngMeta.js). Just need to return the `angular.module` name at the end of the file. I can make the PR if needed.

**Comment by devotis** [comment]
@vinaygopinath Why is this closed? I needed an additional wrapper to get ngMeta to work with webpack.

**Comment by christiaanwesterbeek** [comment]
The change in PR #28 seems inconsistent with the way I'm used to exporting a module. I think we should return the name property. Not sure about the rest of you.

```javascript
return angular.module('ngMeta', [])
  .provider('ngMeta', function() {
    ...
  })
  .name // <-- return the name
```

Without returning the name, I need to 

```javascript
import angular from 'angular'
import 'ng-meta'

export const AppModule = angular
  .module('app', [
    'ngMeta'
  ])
  .name
```

And I would like to:
```javascript
import angular from 'angular'
import ngMeta from 'ng-meta'

export const AppModule = angular
  .module('app', [
    ngMeta
  ])
  .name
```

**Comment by vinaygopinath** [comment]
@devotis Thanks for the suggestion. I'm open for the module to return the name as long as it has no impact on the way the module is imported in other build systems. Would you be willing to test it out with webpack, and, say, gulp and make a new PR?
