### ISSUE TITLE
One of my website meta tags are not initializing

### ISSUE THREAD

**Issue by hyaking** [vinaygopinath/ngMeta#34]
One of my website meta tags are not initializing..Could you please help ..

When am checking in browser it is showing title but when am copying the same in whatsapp or facebook,it is showing as {{meta.title}} and {{meta.description}}.

.config(function ($routeProvider, ngMetaProvider)
{
.when("/", {
                        templateUrl: 'templates/inside.php',
                        controller: 'insideCtrl',
                        meta: {
                            'title': 'Inside Page',
                            'og:title': 'Inside Page',
                            'description': 'Inside Page'
                            'og:description': 'Inside Page'
                        }
                    }
}
myApp.run(function (ngMeta)
{
    ngMeta.init();
})

On Index Page, mentioned as below:
<title>{{ngMeta.title}}</title>
        <meta property="og:title" content="{{ngMeta.title}}" />
        <meta property="og:description" content="{{ngMeta.description}}" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ng-meta/1.0.0/ngMeta.min.js" type="text/javascript"></script>

**Comment by vinaygopinath** [comment]
This does not work for Whatsapp and Facebook, unless you're willing to show the same hard-coded meta tags in all social media snippets. Please refer to the [Support for other crawlers](https://github.com/vinaygopinath/ngMeta#support-for-other-crawlers) section of the README, or this [blog post](http://vinaygopinath.me/blog/tech/social-media-rich-snippets-with-angularjs-and-ngmeta/) for more information.
