### ISSUE TITLE
ngMeta is not initializing any more

### ISSUE THREAD

**Issue by Simobain** [vinaygopinath/ngMeta#36]
ngMeta was working well.
Now it is not initializing any more : 
all my page where ngMeta used to use defaultTags are not working any more.

I recently updated to angular 1.6.

Thanks for you help

**Comment by Simobain** [comment]
Found out what was the issue : 
in angular-ui-router 1.0 $onStateChangeSuccess has been replaced by $transition.on({}, f).

I'm updating ngMeta in consequence.

**Comment by rodrigoyoshida** [comment]
Hi! I was having the same problem here, Angular 1.6 with ui-router 1.0. Could you tell what changes you made or maybe fork this project? It looks like this project is not maintained anymore but I still would like to use this module.

**Comment by Simobain** [comment]
Hi ! 
You could do what taasver said in this issue :
https://github.com/vinaygopinath/ngMeta/issues/25

However, I just downgraded ui-router to 0.3.2 it was less "hacky".

**Comment by vinaygopinath** [comment]
This is a duplicate of #25 and should be fixed in [v1.0.2](https://github.com/vinaygopinath/ngMeta/releases/tag/v1.0.2). Please reopen #25 if you still see this issue.
