### ISSUE TITLE
Will this lib works for Facebook and Twitter? Or they would require server pre-caching of pages?

### ISSUE THREAD

**Issue by Sumit-Chakole** [vinaygopinath/ngMeta#37]

**Comment by vinaygopinath** [comment]
This does not work for Facebook and Twitter, unless you're willing to show the same hard-coded meta tags in all social media snippets. Please refer to the [Support for other crawlers](https://github.com/vinaygopinath/ngMeta#support-for-other-crawlers) section of the README, or this [blog post](http://vinaygopinath.me/blog/tech/social-media-rich-snippets-with-angularjs-and-ngmeta/) for more information.
