### ISSUE TITLE
Not being able to display dynamic content

### ISSUE THREAD

**Issue by MrASousa** [vinaygopinath/ngMeta#38]
Hello,
First of all, I'm pretty lame at JS and Angular, so I'm probably doing some rookie mistake. (Yep, not a programmer)
So, I'm struggling to put dynamic content into the ngMeta.

In my module I have the followed code:

![noticia](https://user-images.githubusercontent.com/17278140/28716921-0bbd81ec-7376-11e7-927a-afb88563ee9c.PNG)

However, it will print like this:

![noticias2](https://user-images.githubusercontent.com/17278140/28716965-38dfbf8c-7376-11e7-8af8-ffc575a8778c.PNG)

How can I make this dynamic?
I tried following the documentation, but there is something I'm not getting it right.

In my controller I tried putting this:
`    ngMeta.setTag('description', 'noticia.NoticiasConteudo)');    `

But I have no idea where to put the ngMeta.setTag, since it didnt work into the   `  <meta name="description" content="{{ngMeta.description}}"> `

Since I got this bomb on my lap and I need to fix it, could anyone help a fellow designer that have no idea what he is doing?

Thanks!

**Comment by chrisrijos** [comment]
This is how you are supposed to reference it.
 content="{{ngMeta['propertyGoesHere']}}"
For future reference these kind of issues should be posted in stackoverflow.
