### ISSUE TITLE
Allow titleSuffix to be set / removed programmatically

### ISSUE THREAD

**Issue by skroonenburg** [vinaygopinath/ngMeta#4]
There are certain pages where I don't want a titleSuffix set, but on the majority I do.

I can't seem to turn off the title suffix programatically. It'd be good if I could do it in 2 ways:

In the route:

```
meta: {
    useTitleSuffix: false
}
```

Programatically:

`ngMeta.useTitleSuffix(false);`

And have that only apply until the next $stateChange

Btw, nice work -- a really useful library :-)

**Comment by vinaygopinath** [comment]
A bit hacky, but this can be done at the moment by setting `titleSuffix` to a blank string `' '`.

In the route/state definition

``` javascript
meta: {
  titleSuffix: ' '
}
```

Programmatically

``` javascript
ngMeta.setTitle('Page title', ' ');
//if the title is already defined in the state
//ngMeta.setTitle($state.current.meta.title, ' ');
```

I can improve this to support `titleSuffix: ''` (empty string) in the state definition, and `ngMeta.setTitle('title', '')` (Skipping the second argument would lead to the default titleSuffix being used)

Thanks :)

**Comment by vinaygopinath** [comment]
This is now available in v0.3.2. To override a default titleSuffix defined in the config, add 

``` javascript
meta: {
  titleSuffix: ''
}
```

or use

``` javascript
ngMeta.setTitle('Page title', '');
```

**Comment by skroonenburg** [comment]
Sorry for the delay in replying -- this is awesome. Thanks for fixing this so quickly!!! We've upgraded & it works a treat.

We're using ngMeta for our AWS certification [online learning platform](https://acloud.guru), if you are interested in who is using your module :-)

**Comment by vinaygopinath** [comment]
Thanks for linking to your site. I've been meaning to list some sites using the ngMeta module in the README, and I'd like to start with yours. Is that okay?

Off-topic, but I'm curious why your site uses `ng-if="ngMeta['tagname']"` on the meta elements. Was that found to be necessary?

**Comment by skroonenburg** [comment]
Yes, that's absolutely fine, can you make it a link to our site? (links
help our SEO!! :-) )

I included the ng-if because some of our pages include particular tags, and
some others don't. We use meta tags so that social media sites can make
rich snippets of our pages... So sometimes we include og:image etc for
Facebook ... It was causing Facebook's debugger to have issues if we had
facebook specific fields there that were empty.
