### ISSUE TITLE
How to use this with AngularJS Route?

### ISSUE THREAD

**Issue by favna** [vinaygopinath/ngMeta#40]
In order for the data to load at all the `ng-app` has to be defined in the `<head>` tag, however that breaks the `ng-scope` required for views for `ng-view`. My question is, how can I have both `ng-app` in the head tag to load meta tags, but still using AngularRoute.

My index.html: https://gist.github.com/Favna/9e585b21b7c7d20a8276e8c7077ea32a

My app.js: https://gist.github.com/Favna/4a298dec0a056742e1c1ad92df17d952

The actual site does load, just the view does not:

![img](https://favna.s-ul.eu/sbyIV2x9.png)

**Comment by vinaygopinath** [comment]
Hi @Favna,

`ng-app` must be defined at the root of the application, typically the `html` element, *not* the `head` element. Could you please try moving the `ng-app` attribute to the `html` element and see if that fixes your issue?

**Comment by favna** [comment]
That does the trick, thanks!
