### ISSUE TITLE
Set up ngMeta as a module

### ISSUE THREAD

**Issue by vinaygopinath** [vinaygopinath/ngMeta#5]
Though ngMeta is available on npm as `ng-meta`, it is not a proper module. ngMeta needs to support commonJS/browserify/AMD.

Recommended reading:
- [UMD](https://github.com/umdjs/umd)
- [Browserify and UMD](http://dontkry.com/posts/code/browserify-and-the-universal-module-definition.html)
- [npm blog - browserify support](http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support)

Thanks @TraaidMark on [SO](http://stackoverflow.com/questions/35010097/how-do-i-load-the-ngmeta-angular-module-with-browserify)

**Comment by traaidmark** [comment]
Ah man thanks for this. Please let me know if I can help with anything.

**Comment by vinaygopinath** [comment]
Thanks @traaidmark. I've released v0.3.2 with CommonJS/Browserify support. Can you check it out and let me know if it works?

**Comment by vinaygopinath** [comment]
npm is mysteriously stuck on the older version 0.3.1 despite publishing 0.3.2. Manually cloning this repo (v0.3.2) and copying it into node_modules works. Will publish v0.3.3 to hopefully push npm to show the latest version.

[demo plnkr](http://plnkr.co/edit/lykpR2uowDELHoYWjow0?p=preview)

**Comment by traaidmark** [comment]
Hey dude, thanks, will test this out during the day!
