### ISSUE TITLE
no description

### ISSUE THREAD

**Issue by stanislavche** [vinaygopinath/ngMeta#9]
html:
`<html lang="ru" ng-app="myApp">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="fragment" content="!" />
    <title ng-bind="ngMeta.title"></title>
    <meta name="description" ng-if="ngMeta.description" content="{{ ngMeta.description }}" />
</head>...`
Localy it work perfect, but when I use it on server, I can't see "description". Title work, but description not(( 
Server use https and there are no console mistakes. 
http://joxi.ru/Vrw6L7fKdwe3AX
I try to use ng-attr-content, but it didn't help.

**Comment by vinaygopinath** [comment]
Looking at the source of [your site](https://design-okna.ru/), the content attribute of the description meta element doesn't seem to be set to `{{ngMeta.description}}`

This is what I see instead.

``` html
<meta name="description" ng-if="ngMeta.description" content="" />
```

Also, I'm not sure if the `ng-if` is necessary for the meta tag.

**Comment by stanislavche** [comment]
May be it's TWIG bug. May be this is my problem: http://stackoverflow.com/questions/13671701/angularjs-twig-conflict-with-double-curly-braces
Today I'll try to fix it and let you know. Something like {{ '{{ngMeta.description}}' }} for TWIG.

**Comment by vinaygopinath** [comment]
I'm going to close this issue, as it doesn't seem to be related to ngMeta. Feel free to reopen it if you find that ngMeta is behaving unexpectedly.

**Comment by stanislavche** [comment]
Thank you, and sorry for openning this issue. Problem was in syntax of twig and angular, they are same and have "{{}}". If you need to use {{ngMeta.description}} use should insert it into twig brackets like this: 
`<meta name="description" content="{{ '{{ngMeta.description}}' }}" />`
